### ISSUE TITLE
Comparison with HTMLPurifier

### ISSUE THREAD

**Issue by stof** [tgalopin/html-sanitizer#11]
It would be great to have a comparison between this package and the HTMLPurifier library which is out there since a long time (what are the differences in the feature they support, etc...)

**Comment by tgalopin** [comment]
I also thought about it and planned to add it to the README. Basically, they don't have the same aim, even if they share some use-cases (HTMLPurifier wants to keep HTML/CSS intact and safe, html-purifier aims at cleaning it and removing anything unexpected). I will write it clearly :) .

**Comment by tgalopin** [comment]
Here it is: https://github.com/tgalopin/html-sanitizer/blob/master/docs/4-comparison-with-htmlpurifier.md :) !
