### ISSUE TITLE
Remove multiple <br> tags

### ISSUE THREAD

**Issue by victorlap** [tgalopin/html-sanitizer#20]
Hi!

Thanks for this great package!

A lot of our html has repeated `<br>` tags like crazy, and I would like to reduce that to just one (or maybe two) line breaks. Is there any way to achieve this result using this package?

Thanks!

**Comment by tgalopin** [comment]
Hello @victorlap,

This feature is not available in core but it should be possible to achieve with a custom extension. You would probably need to create a more advanced extension than what's described in the documentation though. IMO, this extension would need to visit all nodes and strip the <br /> nodes that are too repetitive. If you want to discuss how to create that, don't hesitate to ping me here or on the Symfony slack (symfony.com/support) :) .
