### ISSUE TITLE
Create a static method to pass extensions and `$html`

### ISSUE THREAD

**Issue by ismail1432** [tgalopin/html-sanitizer#21]
In my project *at the moment* I need to purify 2 properties in different entities *with the same extensions*, so I create a simple helper.

```
class SanitizerHelper
{
    private const SANITIZER_WHITE_LIST = ['basic', 'code', 'image', 'list', 'table', 'iframe', 'extra'];

    public static function sanitize(string $html)
    {
        $sanitizer = Sanitizer::create(['extensions' => self::SANITIZER_WHITE_LIST]);

        return $sanitizer->sanitize($html);
    }
}
```

The idea is to create a static method to pass extensions as first args and content as second args : 
Actual
```
 $sanitizer = Sanitizer::create(['extensions' => self::SANITIZER_WHITE_LIST]);
 $safeHtml = sanitizer->sanitize($untrustedHtml);
```

After
```
$safeHtml = HtmlSanitizer\Sanitizer::sanitize([
    'extensions' => ['basic', 'code', 'image', 'list', 'table', 'iframe', 'details', 'extra'],
     $untrustedHtml)
```
WDYT ?

**Comment by tgalopin** [comment]
Why do you think this would be more useful than `Sanitizer::create(['extensions' => ['basic', 'code', 'image', 'list', 'table', 'iframe', 'extra']])->sanitize($html)`?

**Comment by ismail1432** [comment]
It's not more useful TBH I did not think to your method ! 
Thanks
