### ISSUE TITLE
How can I allow "target=_blank" ? 

### ISSUE THREAD

**Issue by Phroggy78** [tgalopin/html-sanitizer#47]
Hi @tgalopin & all

This package is extremely useful, thanks for all the hard work. 
I am currently using it in a site where I need to be able to set a target when for certain links. Is there a simple way to configure this ? 

I'm already using an extension provided by @olegatro to allow relative URI's. I thought perhaps it would be possible to modify that extension ? 

Thanks for any help, 
PhR

**Comment by Phroggy78** [comment]
After reading in detail the documentation, I understood how to do it !! it works perfectly. 
"when all else fails, read the documentation" ;-)

**Comment by olegatro** [comment]
Can you give a work example ?
