### ISSUE TITLE
&nbsp; is getting converted to 00a0

### ISSUE THREAD

**Issue by rohitcoder** [tgalopin/html-sanitizer#48]
Hi @tgalopin  I am using this sanitizer for sanitizing HTML Text, i noticed its converting ``&nbsp;`` to ``00a0`` any idea how to fix this issue?

**Comment by tgalopin** [comment]
Hum, that's super weird! Any idea where it may come from? Would you have a reproducer?

**Comment by rohitcoder** [comment]
Hi i tried to reproduce this issue in separate file and it was working fine, after investigation i found that  i was converting sanitized test to ``json_encode()`` and during that conversion ``&nbsp;`` was getting converted into ``u00a0``.

This issue is not related with html-sanitizer 
I solved this issue by adding second args ``JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES`` in json_encode()

Now, everything is working fine, thanks :) !
