### ISSUE TITLE
Add support for u (unarticulated) tag

### ISSUE THREAD

**Issue by fbastien** [tgalopin/html-sanitizer#58]
Although ``u`` (as in underline) tag has been deprecated in HTML 4.01, ``u`` tag has been redefined in HTML 5 ("u" as in unarticulated). Thus, I think it should be included in the ``basic`` extension.

**Comment by tgalopin** [comment]
Can you open a PR for that :) ? That's a good idea

**Comment by fbastien** [comment]
Sure, I'll give it a try :)

**Comment by angelomelonas** [comment]
Any updates on this one? :)

**Comment by fbastien** [comment]
Haven't tried yet... hopefully this week-end :)

**Comment by angelomelonas** [comment]
@fbastien I went ahead and implemented it locally so long. Maybe I can also create a PR? 😄

**Comment by fbastien** [comment]
@angelomelonas Sure, feel free to create the corresponding PR 😉

**Comment by fbastien** [comment]
@tgalopin Better late than never, I created PR #61 for this

**Comment by angelomelonas** [comment]
@fbastien totally forgot about this until now. My apologies 🙈 Thanks so much for the PR though!
