### ISSUE TITLE
<u> tag not supported

### ISSUE THREAD

**Issue by adriflorence** [tgalopin/html-sanitizer#64]
Hi,
I am using html/sanitizer version 1.4.0 in a Symfony project, and the Sanitizer filters out the `<u>` tags even though it is explicitly configured in the tags section as in the [configuration reference file](https://github.com/tgalopin/html-sanitizer/blob/d2dd64cf1a3739167802aa00217df0f17e67372a/docs/3-configuration-reference.md). 

```
      $sanitizer = Sanitizer::create([
          'extensions' => ['basic', 'code', 'image', 'list', 'table', 'details', 'extra'],
          'tags' => [
              'u' => [
                  'allowed_attributes' => [],
              ],
          ],
      ]);
```

I noticed there was a PR (#61) for adding `<u>` tags into the basic extension but it's not been released yet. Are tags only available from within extensions? So until that commit is released there will be no support for `<u>` tags?
Could someone please advise?

Thanks a lot!

**Comment by huynguyen93** [comment]
I have the same issue

**Comment by fbastien** [comment]
@adriflorence Indeed support for `<u>` tag (and documentation mentioning it) was merged in the repository but not released yet. In order to handle `<u>` tags you have to either wait for next version to be released, or create your own extension in your project in the meantime.

**Comment by tgalopin** [comment]
It is now!
